name: Async.Locks CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ulfbou/dotnet-node:9.0
    env:
      PROJECT_ROOT_DIR: /github/workspace
      SRC_DIR: /github/workspace/Src
      SRC_PROJECT: /github/workspace/Src/Async.Locks.csproj
      TEST_DIR: /github/workspace/Tests
      TEST_PROJECT: /github/workspace/Tests/Async.Locks.csproj
      BENCHMARKS_DIR: /github/workspace/Benchmarks/Async.Locks.Benchmarks.csproj
      BENCHMARKS_PROJECT: /github/workspace/Benchmarks/Async.Locks.Benchmarks.csproj
      TEST_RESULTS_DIR: /github/workspace/TestResults
      GIT_VERSION_PROPS: /github/workspace/gitversion.props
      BUILD_OUTPUT_DIR: /github/workspace/build-output
      BENCHMARK_RESULTS_DIR: /github/workspace/benchmark-results
      UBUNTU_SCRIPTS_DIR: "/github/workspace/scripts/ubuntu"
      SCRIPTS_DIR: "/github/workspace/scripts"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Create .NET Tool Manifest
        run: dotnet new tool-manifest
        working-directory: ${{ env.PROJECT_ROOT_DIR }}

      - name: Install GitVersion.Tool locally
        run: dotnet tool install --local GitVersion.Tool

      - name: Run GitVersion and Create gitversion.props
        id: gitversion
        run: |
          DOTNET_TOOLS_DIR="$HOME/.dotnet/tools"
          if [ -d "$DOTNET_TOOLS_DIR" ] && [ -f "$DOTNET_TOOLS_DIR/dotnet-gitversion" ]; then
            gitversion_output="$("$DOTNET_TOOLS_DIR/dotnet-gitversion" /output json)"
            echo "##[set-output name=major]::$(echo "$gitversion_output" | jq -r '.Major')"
            echo "##[set-output name=minor]::$(echo "$gitversion_output" | jq -r '.Minor')"
            echo "##[set-output name=patch]::$(echo "$gitversion_output" | jq -r '.Patch')"
            echo "##[set-output name=semver]::$(echo "$gitversion_output" | jq -r '.SemVer')"
            echo "##[set-output name=informationalversion]::$(echo "$gitversion_output" | jq -r '.InformationalVersion')"
            echo "##[set-output name=majorMinorPatch]::$(echo "$gitversion_output" | jq -r '.MajorMinorPatch')"

            major=$(echo "$gitversion_output" | jq -r '.Major')
            minor=$(echo "$gitversion_output" | jq -r '.Minor')
            patch=$(echo "$gitversion_output" | jq -r '.Patch')
            assembly_version="${major}.${minor}.${patch}.0"

            echo "<Project>" > gitversion.props
            echo "  <PropertyGroup>" >> gitversion.props
            echo "    <AssemblyVersion>${assembly_version}</AssemblyVersion>" >> gitversion.props
            echo "    <FileVersion>$(echo "$gitversion_output" | jq -r '.SemVer')</FileVersion>" >> gitversion.props
            echo "    <Version>$(echo "$gitversion_output" | jq -r '.SemVer')</Version>" >> gitversion.props
            echo "    <InformationalVersion>$(echo "$gitversion_output" | jq -r '.InformationalVersion')</InformationalVersion>" >> gitversion.props
            echo "  </PropertyGroup>" >> gitversion.props
            echo "</Project>" >> gitversion.props

            echo "Generated gitversion.props"
          else
            echo "Error: dotnet-gitversion executable not found in $DOTNET_TOOLS_DIR."
            exit 1
          fi
        env:
          PROJECT_ROOT: ${{ github.workspace }}

      # Temporarily disable artifact upload for local testing with 'act'
      # - name: Upload GitVersion Props Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: gitversion-props
      #     path: gitversion.props
      #     if-no-files-behavior: error

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_ROOT_DIR }}/Async.Locks.sln

      - name: Build project
        run: dotnet build ${{ env.PROJECT_ROOT_DIR }}/Async.Locks.sln --configuration Release --output ${{ env.BUILD_OUTPUT_DIR }}

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ulfbou/dotnet-node:9.0
    env:
      PROJECT_ROOT_DIR: /github/workspace
      SRC_DIR: /github/workspace/Src
      SRC_PROJECT: /github/workspace/Src/Async.Locks.csproj
      TEST_DIR: /github/workspace/Tests
      TEST_PROJECT: /github/workspace/Tests/Async.Locks.csproj
      BENCHMARKS_DIR: /github/workspace/Benchmarks/Async.Locks.Benchmarks.csproj
      BENCHMARKS_PROJECT: /github/workspace/Benchmarks/Async.Locks.Benchmarks.csproj
      TEST_RESULTS_DIR: /github/workspace/TestResults
      GIT_VERSION_PROPS: /github/workspace/gitversion.props
      BUILD_OUTPUT_DIR: /github/workspace/build-output
      BENCHMARK_RESULTS_DIR: /github/workspace/benchmark-results
      UBUNTU_SCRIPTS_DIR: "/github/workspace/scripts/ubuntu"
      SCRIPTS_DIR: "/github/workspace/scripts"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Download GitVersion props artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: gitversion-props
      #     path: .

      - name: Run unit tests (Async.Locks.Tests)
        run: |
          mkdir -p ${{ env.TEST_RESULTS_DIR }}
          dotnet test Async.Locks.Tests.csproj --configuration Release --logger:"trx;LogFileName=${{ env.TEST_RESULTS_DIR }}/test-results.trx" --settings codecoverage.runsettings -p:Parallelize=true
        working-directory: ${{ env.TEST_DIR }}
        continue-on-error: false

  benchmark:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ulfbou/dotnet-node:9.0
    env:
      PROJECT_ROOT_DIR: /github/workspace
      SRC_DIR: /github/workspace/Src
      SRC_PROJECT: /github/workspace/Src/Async.Locks.csproj
      TEST_DIR: /github/workspace/Tests
      TEST_PROJECT: /github/workspace/Tests/Async.Locks.csproj
      BENCHMARKS_DIR: /github/workspace/Benchmarks/Async.Locks.Benchmarks.csproj
      BENCHMARKS_PROJECT: /github/workspace/Benchmarks/Async.Locks.Benchmarks.csproj
      TEST_RESULTS_DIR: /github/workspace/TestResults
      GIT_VERSION_PROPS: /github/workspace/gitversion.props
      BUILD_OUTPUT_DIR: /github/workspace/build-output
      BENCHMARK_RESULTS_DIR: /github/workspace/benchmark-results
      UBUNTU_SCRIPTS_DIR: "/github/workspace/scripts/ubuntu"
      SCRIPTS_DIR: "/github/workspace/scripts"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Download GitVersion props artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: gitversion-props
      #     path: .

      - name: Run benchmarks
        run: |
          mkdir -p ${{ env.TEST_RESULTS_DIR }}
          dotnet run --project ${{ env.BENCHMARKS_DIR }} --configuration Release -f net9.0 -o ${{ env.BENCHMARK_RESULTS_DIR }}
        working-directory: /github/workspace

      - name: Analyze Benchmark Results
        run: |
          echo "Placeholder for Analyzing benchmark results..."

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'
    container:
      image: ulfbou/dotnet-node:9.0
    env:
      PROJECT_ROOT_DIR: /github/workspace
      SRC_DIR: /github/workspace/Src
      SRC_PROJECT: /github/workspace/Src/Async.Locks.csproj
      TEST_DIR: /github/workspace/Tests
      TEST_PROJECT: /github/workspace/Tests/Async.Locks.csproj
      BENCHMARKS_DIR: /github/workspace/Benchmarks/Async.Locks.Benchmarks.csproj
      BENCHMARKS_PROJECT: /github/workspace/Benchmarks/Async.Locks.Benchmarks.csproj
      TEST_RESULTS_DIR: /github/workspace/TestResults
      GIT_VERSION_PROPS: /github/workspace/gitversion.props
      BUILD_OUTPUT_DIR: /github/workspace/build-output
      BENCHMARK_RESULTS_DIR: /github/workspace/benchmark-results
      UBUNTU_SCRIPTS_DIR: "/github/workspace/scripts/ubuntu"
      SCRIPTS_DIR: "/github/workspace/scripts"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Load .env file
        uses: jpfulton/github-action-dotenv-load@v1
        with:
          path: .env

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore Async.Locks.sln

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ${{ env.BUILD_OUTPUT_DIR }}

      - name: Download GitVersion props artifact
        uses: actions/download-artifact@v4
        with:
          name: gitversion-props
          path: .

      - name: Pack NuGet package
        run: dotnet pack ${{ env.SRC_PROJECT }} --configuration Release --output ${{ env.BUILD_OUTPUT_DIR }} -p:PackageVersion=${{ steps.gitversion.outputs.semver }}

      - name: Publish NuGet package
        run: dotnet nuget push ${{ env.BUILD_OUTPUT_DIR }}/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ env.NUGET_API_KEY }}
