name: Async.Locks CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Environment
        run: |
          chmod +x ./scripts/ubuntu/setup.sh
          ./scripts/ubuntu/setup.sh
        shell: bash

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore Async.Locks.sln --lock-file

      - name: Build project
        run: dotnet build Async.Locks.sln --configuration Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ${{ env.BUILD_OUTPUT_DIR }}

      - name: Debug Build Artifacts
        run: ls -R ${{ env.BUILD_OUTPUT_DIR }}

      - name: Upload GitVersion props
        uses: actions/upload-artifact@v4
        with:
          name: gitversion-props
          path: ${{ env.GIT_VERSION_PROPS }}

      - name: Debug GitVersion props
        run: ls -R

      - name: Cache .dotnet tools
        uses: actions/cache@v3
        with:
          path: ~/.dotnet/tools
          key: ${{ runner.os }}-dotnet-tools-${{ hashFiles('./scripts/ubuntu/setup.sh') }}-gitversion-latest

      - name: Run unit tests
        run: dotnet test ${{ env.TEST_PROJECT }} --configuration Release --logger:"trx;LogFileName=test-results.trx" --settings codecoverage.runsettings -p:Parallelize=true
        continue-on-error: false

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ env.TEST_RESULTS_DIR }}

      - name: Run benchmarks
        run: dotnet run --project ${{ env.BENCHMARKS_DIR }} --configuration Release -f net9.0

      - name: Analyze Benchmark Results
        run: ./scripts/ubuntu/analyze-benchmarks.sh ${{ env.BENCHMARK_RESULTS_DIR }}

  publish:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore Async.Locks.sln

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: Async.Locks/bin/Release/net9.0/

      - name: Download GitVersion props
        uses: actions/download-artifact@v4
        with:
          name: gitversion-props

      - name: Pack NuGet package
        run: dotnet pack ${{ env.SRC_PROJECT }} --configuration Release --output . -p:Version=$(cat ${{ env.GIT_VERSION_PROPS }} | grep AssemblyVersion | cut -d '=' -f2)

      - name: Publish NuGet package
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
