name: Async.Locks Debugging CI/CD

on:
  push:
    branches:
      - development/github-workflows
  pull_request:
    branches:
      - development/github-workflows

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ulfbou/dotnet-node:9.0
    env:
      PROJECT_ROOT: /github/workspace
      SLN_FILE: /github/workspace/Async.Locks.sln
      SRC_DIR: /github/workspace/Src
      LOCKS_PROJECT_FILE: /github/workspace/Src/Async.Locks.csproj
      TEST_DIR: /github/workspace/Tests
      TESTS_PROJECT_FILE: /github/workspace/Tests/Async.Locks.Tests.csproj
      BENCHMARKS_DIR: /github/workspace/Benchmarks
      BENCHMARKS_PROJECT_FILE: /github/workspace/Benchmarks/Async.Locks.Benchmarks.csproj
      BUILD_OUTPUT_DIR: /github/workspace/build-output
      TEST_RESULTS_DIR: /github/workspace/TestResults
      BENCHMARK_RESULTS_DIR: /github/workspace/benchmark-results
      CODECOVERAGE_SETTINGS_FILE: /github/workspace/codecoverage.runsettings
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Run GitVersion
        id: gitversion
        run: |
          echo "Current PATH: $PATH"
          echo "Checking for dotnet-gitversion using 'dotnet tool run'..."
          if dotnet tool run dotnet-gitversion --version; then
            echo "dotnet-gitversion found and version displayed."
          else
            echo "dotnet-gitversion NOT found using 'dotnet tool run'."
          fi
          gitversion_output="$("dotnet tool run dotnet-gitversion" /output json)"
          echo "GitVersion Output (JSON):"
          echo "$gitversion_output"
          echo "##[set-output name=major]::$(echo "$gitversion_output" | jq -r '.Major')"
          echo "##[set-output name=minor]::$(echo "$gitversion_output" | jq -r '.Minor')"
          echo "##[set-output name=patch]::$(echo "$gitversion_output" | jq -r '.Patch')"
          echo "##[set-output name=semver]::$(echo "$gitversion_output" | jq -r '.SemVer')"
          echo "##[set-output name=informationalversion]::$(echo "$gitversion_output" | jq -r '.InformationalVersion')"
          echo "##[set-output name=majorMinorPatch]::$(echo "$gitversion_output" | jq -r '.MajorMinorPatch')"
        shell: bash