name: Async.Locks CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ulfbou/dotnet-node:9.0
    env:
      PROJECT_ROOT: /github/workspace
      SLN_FILE: /github/workspace/Async.Locks.sln
      SRC_DIR: /github/workspace/Src
      LOCKS_PROJECT_FILE: /github/workspace/Src/Async.Locks.csproj
      TEST_DIR: /github/workspace/Tests
      TESTS_PROJECT_FILE: /github/workspace/Tests/Async.Locks.Tests.csproj
      BENCHMARKS_DIR: /github/workspace/Benchmarks
      BENCHMARKS_PROJECT_FILE: /github/workspace/Benchmarks/Async.Locks.Benchmarks/Async.Locks.Benchmarks.csproj
      BUILD_OUTPUT_DIR: /github/workspace/build-output
      TEST_RESULTS_DIR: /github/workspace/TestResults
      BENCHMARK_RESULTS_DIR: /github/workspace/benchmark-results
      CODECOVERAGE_SETTINGS_FILE: /github/workspace/codecoverage.runsettings
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
